"""Build the probe-isolation table."""

from __future__ import annotations

import collections

from .common import (
    ALL_RUNGS,
    LADDER,
    TABLE_ROOT,
    bundle_path,
    mean,
    num,
    read_per_sample,
    write_manifest,
)

OUT_DIR = TABLE_ROOT

REPORT_RUNG = LADDER[0]


CHANNELS = [
    ("reword", "anchor_reword"),
    ("reorder", "anchor_reorder"),
    ("reseg", "anchor_reseg"),
]

ATOMS = [
    ("controlled_reorder", "reorder"),
    ("synonym_substitution", "reword"),
    ("split_midpoint", "reseg"),
    ("merge_adjacent", "reseg"),
]


def probe_ratio(attack: str) -> float:
    return float(attack.split("ratio=")[1])


def main() -> None:
    bundle = bundle_path()
    rows = read_per_sample(bundle)

    grouped: dict[tuple[str, str], list[dict]] = collections.defaultdict(list)
    for row in rows:
        if row["stage"] != "attack" or "ratio=" not in row["attack"]:
            continue
        for rung in ALL_RUNGS:
            if rung.matches(row):
                grouped[(rung.key, row["attack"])].append(row)
                break

    body: list[str] = []
    notes: list[str] = []
    worst_off_target = 0.0
    worst_where = ""

    for index, (atom, target) in enumerate(ATOMS):
        attacks = sorted(
            (a for (k, a) in grouped if k == REPORT_RUNG.key and a.startswith(atom)),
            key=probe_ratio,
        )
        if not attacks:
            raise SystemExit(
                f"{REPORT_RUNG.key}: missing required isolation probe {atom}"
            )

        if index:
            body.append(r"\addlinespace[2pt]")

        for position, attack in enumerate(attacks):
            cell = grouped[(REPORT_RUNG.key, attack)]
            escaped = atom.replace("_", r"\_")
            name = rf"\texttt{{{escaped}}}" if position == 0 else ""
            fields = []
            for label, column in CHANNELS:
                value = mean([num(r, column) for r in cell])
                text = f"{value:.3f}"
                fields.append(rf"\textbf{{{text}}}" if label == target else text)
            body.append(
                f"{name} & {probe_ratio(attack):.2f} & " + " & ".join(fields) + r" \\"
            )

        for rung in ALL_RUNGS:
            for attack in (a for (k, a) in grouped
                           if k == rung.key and a.startswith(atom)):
                cell = grouped[(rung.key, attack)]
                for label, column in CHANNELS:
                    if label == target:
                        continue
                    value = mean([num(r, column) for r in cell])
                    if value == value and value > worst_off_target:
                        worst_off_target = value
                        worst_where = f"{atom} at {attack.split('=')[1]} on {rung.key}, {label}"

        notes.append(f"{atom:22s} {len(attacks)} intensities on {REPORT_RUNG.key}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUT_DIR / "isolation.tex", "w") as fh:
        fh.write("% Generated by python -m visualization extract -- do not edit.\n")
        fh.write("\\newcommand{\\isolationrows}{%\n")
        for line in body:
            fh.write(line + "\n")
        fh.write("}\n")
        fh.write("\\newcommand{\\isolationworstofftarget}"
                 f"{{{worst_off_target:.3f}}}\n")

    notes.append("")
    notes.append(f"reported rung: {REPORT_RUNG.key} ({REPORT_RUNG.label})")
    notes.append(
        f"worst off-target reading over all rungs: {worst_off_target:.3f} "
        f"({worst_where})"
    )
    write_manifest(OUT_DIR / "MANIFEST.txt", bundle, notes)

    print(f"isolation: wrote {len(body)} rows to {OUT_DIR / 'isolation.tex'}")
    print(f"  worst off-target reading over all rungs: {worst_off_target:.3f} "
          f"({worst_where})")
    for note in notes:
        if note.startswith("MISSING"):
            print("  " + note)


if __name__ == "__main__":
    main()
