"""Build the appendix table of clean fidelity and its four criteria.

Run through ``python -m visualization extract``.
"""

from __future__ import annotations

import math

from .common import (
    FRONTIER_SCHEMES,
    TABLE_ROOT,
    bundle_path,
    num,
    read_cell_summary,
    write_manifest,
)

OUT_DIR = TABLE_ROOT

LABELS = {
    "semstamp": r"\semstamp",
    "ksemstamp": r"\ksemstamp",
    "pmark-online": r"\pmark\ (online)",
    "samark": r"\samark",
    "swordstamp": r"\ourstamp",
    "kswordstamp": r"\kourstamp",
}

CRITERIA = (
    ("fluency", "llm_quality_fluency"),
    ("coherence", "llm_quality_coherence"),
    ("relevance", "llm_quality_relevance"),
    ("informativeness", "llm_quality_informativeness"),
)

OVERALL = ("overall fidelity", "llm_quality")


def unwatermarked_row(rows: list[dict]) -> dict:
    """Return the unique clean no-watermark quality baseline."""
    matches = [
        row for row in rows
        if row["family"] == "none"
        and row["stage"] == "watermark"
        and row["attack"] == "none"
    ]
    if len(matches) != 1:
        raise SystemExit(
            "expected one clean no-watermark row, found "
            f"{len(matches)}"
        )
    return matches[0]


def clean_row(rows: list[dict], key: str) -> dict:
    """Return the unique clean watermark row for one reported scheme."""
    configuration = next(item for item in FRONTIER_SCHEMES if item.key == key)
    matches = [
        row for row in rows
        if configuration.matches(row)
        and row["stage"] == "watermark"
        and row["attack"] == "none"
    ]
    if len(matches) != 1:
        raise SystemExit(
            f"{key}: expected one watermark row with attack=none, "
            f"found {len(matches)}"
        )
    return matches[0]


def format_estimate(row: dict, key: str) -> str:
    """Format a percentage mean followed by its two-sided 95% t interval."""
    mean = num(row, key)
    half_width = num(row, f"{key}_ci")
    if math.isnan(mean) or math.isnan(half_width):
        raise SystemExit(f"missing {key} or {key}_ci")
    lower = 100.0 * (mean - half_width)
    upper = 100.0 * (mean + half_width)
    return f"{100.0 * mean:.1f} [{lower:.1f},{upper:.1f}]"


def main() -> None:
    bundle = bundle_path()
    rows = read_cell_summary(bundle)
    clean_rows = {key: clean_row(rows, key) for key in LABELS}
    baseline = unwatermarked_row(rows)

    for key, row in (("unwatermarked", baseline), *clean_rows.items()):
        criterion_means = [num(row, field) for _, field in CRITERIA]
        if not math.isclose(
            sum(criterion_means) / len(criterion_means),
            num(row, OVERALL[1]),
            rel_tol=0.0,
            abs_tol=1e-12,
        ):
            raise SystemExit(f"{key}: criterion means do not reproduce fidelity")

    def criterion_gaps(base: str, final: str) -> list[float]:
        return [
            100.0 * (num(clean_rows[base], field) - num(clean_rows[final], field))
            for _, field in CRITERIA
        ]

    sword_gaps = criterion_gaps("semstamp", "swordstamp")
    ksword_gaps = criterion_gaps("ksemstamp", "kswordstamp")
    body = [
        r"% Generated by python -m visualization extract -- do not edit.",
        rf"\newcommand{{\resultSwordCriterionGapMin}}{{{min(sword_gaps):.1f}}}",
        rf"\newcommand{{\resultSwordCriterionGapMax}}{{{max(sword_gaps):.1f}}}",
        rf"\newcommand{{\resultKSwordCriterionGapMin}}{{{min(ksword_gaps):.1f}}}",
        rf"\newcommand{{\resultKSwordCriterionGapMax}}{{{max(ksword_gaps):.1f}}}",
        r"\newcommand{\qualitycriteriarows}{%",
    ]
    notes = []
    baseline_estimates = [
        format_estimate(baseline, field)
        for _, field in (*CRITERIA, OVERALL)
    ]
    body.append("Unwatermarked & " + " & ".join(baseline_estimates) + r" \\")
    body.append(r"\addlinespace[2pt]")
    notes.append(f"unwatermarked  n={baseline['n_samples']}")
    for index, key in enumerate(LABELS):
        row = clean_rows[key]
        if index == 4:
            body.append(r"\addlinespace[2pt]")
        estimates = [
            format_estimate(row, field)
            for _, field in (*CRITERIA, OVERALL)
        ]
        body.append(LABELS[key] + " & " + " & ".join(estimates) + r" \\")
        notes.append(f"{key:14s} n={row['n_samples']}")
    body.append("}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUT_DIR / "quality_criteria.tex", "w") as handle:
        handle.write("\n".join(body) + "\n")

    notes.insert(
        0,
        "columns: fluency, coherence, relevance, informativeness, "
        "overall fidelity",
    )
    notes.insert(1, "cells: percentage mean [two-sided 95% Student-t CI]")
    notes.insert(2, "unit: documents after averaging three judge runs per document")
    notes.insert(3, "scope: clean unwatermarked and watermarked text")
    write_manifest(
        OUT_DIR / "QUALITY_CRITERIA_MANIFEST.txt",
        bundle,
        notes,
        uncertainty="two-sided 95% Student-t CI across document means",
    )
    print(f"quality criteria: wrote {len(LABELS) + 1} rows to "
          f"{OUT_DIR / 'quality_criteria.tex'}")


if __name__ == "__main__":
    main()
